### ISSUE TITLE
Steam dir taking up drive space?

### ISSUE THREAD

**Issue by Chris230291** [arkmanager/ark-server-tools#1010]
Hi. Why does the steam dir keep downloads? Is it supposed to? The mods etc get copied over to the ARK dir but why not moved or deleted after?

Thanks :)

**Comment by klightspeed** [comment]
You can delete mods from the Steam workshop directory after installing them by using the `arkmanager remove-mods --args <mod1> <mod2> ...`

If you want to remove all mods from the Steam workshop directory after installing them, you can remove the entire `~/Steam/steamapps/workshop` directory.

Note that this will break mod update detection, as the workshop manifest is used to detect if a mod update is available.  Simply removing the mod's directory can cause the next mod update to be broken, so that remove-mods command also removes it from the manifest, which will result in an update always being detected the next time an update is checked for.  Note that the mod file stored in the Mods directory does _not_ contain the mod version, and so cannot be used to determine if a mod update is available.

**Comment by Chris230291** [comment]
Ah OK thanks for the reply. Ye thats a problem.

I am using these tools inside a docker container. The ARK install volume is large enough that this doesnt matter, but the OS root volume isnt. I am not sure how to make the image also store Steam on the larger volume. I think it would need a rewrite. Offtopic but would be nice if we had an offical docker image :)

I think ARK Server Manager or something else makes a file for each mod to monitor versions. Is that not something that can be done here?

Chris

**Comment by klightspeed** [comment]
You can try symlinking the `Steam` directory to a directory in your container volume in the docker startup script.

**Comment by klightspeed** [comment]
41556ff should add support for checking the installed mod version against the version on Steam.

**Comment by Chris230291** [comment]
Thanks. So the latest version should not need to maintain separate downloads?
