### ISSUE TITLE
Server not automatically updating Mods on all Servers

### ISSUE THREAD

**Issue by fusselshu** [arkmanager/ark-server-tools#1028]
I am experiencing a weird issue.
We are running a root server hosting 4 Ark Servers connected within a cluster.
For about 2 weeks now, arkmanager is not automatically updating all 4 Servers, only the first or only the first and second server.
All log entrys below the timestamp "2019-07-12 01:29:53" are done manually with "arkmanager checkmodupdate @all"
Cronjob to update Server and Mods:
```
0 * * * * /usr/local/bin/arkmanager --cronjob update @all  --saveworld --warn --update-mods --args  -- >/dev/null 2>&1
```
 Arkmanager Version:
```
Version: 1.6
Channel: master
Commit: 5d839a7
Release Tag: v1.6.47
Blob SHA: 17673f8d40e090d1b57e371a274b0c3781b0995d
```

![arkmanager_log](https://user-images.githubusercontent.com/52514278/61092501-ca49a200-a446-11e9-86e5-09d85a4492b6.png)

**Comment by klightspeed** [comment]
That looks almost as if you used `&` instead of `&&` when chaining checkmodupdate / update / restart commands together.  `&` will background the previous command, while `&&` will only execute the next command if the previous command succeeds.

**Comment by fusselshu** [comment]
Hey, thanks for the fast reply :)
What do you mean by "&" and "&&"?

**Comment by ftmflea** [comment]
I'm getting something similar.  Mod updates on first map, but the rest fail to notice there's an update with the mod.  When I try to log in I get a mod version mismatch.  checkmodupdate returns All mods are up to date.  My cron is:
*/15 * * * * /usr/local/bin/arkmanager update --update-mods --safe --warn --backup @all > /var/log/arktools/cron.log
Dunno if it matters, but they all share a staging dir.

**Comment by fusselshu** [comment]
Ah right, I had also set the staging to true with a directory for it, disabled it like a week ago, since i thought aswell, that it is causing this problem.

**Comment by TheMourningWolf** [comment]
Just so we are clear on how far this reaches if it is a problem in the tools. I am having a similar issue and I have been updating my servers manually the whole time. It started about 3 weeks ago i'd say?

I log in and enter these commands:
arkmanager stop @all
arkmanager update --update-mods @all

after that it goes through and updates the first instance both ark and the mods
then it seems to skip updating the mods on every other instance but still updates ark

As others have said when I check to see if a instance has outdated mods via
arkmanager checkmodupdate @<instancenamehere>
it just returns that all mods are up to date even if they arent. the update screen never said it was downloading updates for it and never did because upon starting all instances only the first one has the correct mods.

The only workaround I have found for this is to update ark itself if it needs it then run arkmanager installmods @all
this forces it to grab all of the mods regardless of whether it needs to or not

Version: 1.6
Channel: master
Commit: f69ba15
Release Tag: v1.6.53
Blob SHA: 6d19e8bff03048aec6541c7301512df6f4d30500

All of my instances are separate directories that are clustered.

**Comment by Alphakilo** [comment]
@TheMourningWolf If the error persists, please create a new issue.
