### ISSUE TITLE
Cluster Start Problems

### ISSUE THREAD

**Issue by M0ntyzuma** [arkmanager/ark-server-tools#1128]
Aloha, 
Maybe anyone knows what to do:
we run an Ark Cluster for over an year, now we have all 9 Maps running and all was fine.
In the last ~8 Weeks we have an Major Problem, the servers starting not correct.
aberration starts with extinction map or center with ragnarok etc,..   one of that twistet server run correct and on the other we have an Connection Timeout. 
We have to check  every single server after an cluster restart ...
Steam and ark say that the correct server is running...   TheCenter  if i join that server it loads the ragnarok map.
We have to restart the   affected Servers multiple times... and check the map after every  start with an login.  That Consumes a lot of time.

**Comment by Eruth-Ikero** [comment]
Hello toghether,

I´m an admin cooperating with M0ntyzuma an here I have some additional information about our problem:

Hosted are 9 instances on 1 root server:
01 - Island - running fine
02 - Center - running mostly fine
03 - Scorched - not running
04 - Ragnarok - running sometimes
05 - Aberration - not running
06 - Extinction - running mostly fine
07 - Valguero - not running
08 - Crystal - running mostly fine
09 - Genesis - not running

Not running Servers are switching Maps, what means you can see correct server name at Steam and ingame browser, but when you join you are switched to another map (for example you join Aberration and end up at Scorched) with correct savegame of the switched map. If you directly join the switched Server (as in the example above you join Scorched directly) you get error message "Connection Timeout".

Mostly running servers have the same issue then not running server, but after a few restarts they are working.

Our Cluster is fully managed and modded via ark-server-tools, running without any problems since 3 years through Debian 9.
Every server has its own instance.cfg, but they share gameusersettings.ini and game.ini.
Ark-server-tools is installed as a user installation via user steam, same with steamcmd.

IPtables are set up for both TCP and UDP with following ports:
Queryport 27015 - 27095 (inccrement of 10 per server)
Gameport 7777 - 7786 (increment of 1 per server, leaving 7781 unused since it didn´t worked)
RCONport 32330 - 32338 (increment of 1 per server)

I attached 2 server instance configs as txt-files.


[01-island.txt](https://github.com/FezVrasta/ark-server-tools/files/4993405/01-island.txt)
[03-scorched.txt](https://github.com/FezVrasta/ark-server-tools/files/4993407/03-scorched.txt)

**Comment by klightspeed** [comment]
You need to leave 2 ports between server ports, as each server will bind to both Port and Port+1 since 311.74 (released June 11th 2020)

**Comment by M0ntyzuma** [comment]
Ok, We have Changed the ports  to 7778 ... 7780 etc and the Cluster works fine. Thanks.
