### ISSUE TITLE
!chatcommands

### ISSUE THREAD

**Issue by Log1x** [arkmanager/ark-server-tools#564]
Hi. I have a feature request and figured it may be doable with the addition to "chatCommandRestartCancel" in 1.6-dev.

Could we get something in the config where we can add custom commands? Of course, this would need instance support.

I'd love to be able to add commands like:

**!rates**
serverchat TestServer: Server Rates: 5x Taming, 5x Experience, 5x Gathering

**!website**
serverchat TestServer: [Website] https://example.com

**Potential configuration layout**

```
chatCommandTrigger="!"
chatCommand_rates="serverchat TestServer: [Server Rates] 5x Taming, 5x Experience, 5x Gathering"
chatCommand_website="serverchat TestServer: [Website] https://example.com"
```

Please let me know your thoughts. This would be amazing.

Thanks a ton for your server wrapper! It's great!

**EDIT:** Did some minor refactoring as we'd more than likely want the commands to let you insert your own RCON-based command whether it be broadcast, serverchat, SaveWorld, etc. -- I also removed the "chatName" variable as it is unnecessary.

**Comment by arkfrance** [comment]
Yeah should be good !

**Comment by klightspeed** [comment]
There are a couple of ways this could be done - monitoring the ServerGame.log (which requires the 
`-servergamelog` option), or periodically executing the `GetChat` RCON command (which fetches and clears the chat buffer).

If it's the former, it could be done during the server monitoring loop in doRun.

If it's the latter, it might be best if it were another process that is e.g. enabled by a flag, and that logs chat to a chat log.

**Comment by arkfrance** [comment]
Servergamelog is still buggy for now, I think they don't care about it... The gettchat would be better I guess

**Comment by arkfrance** [comment]
https://survivetheark.com/index.php?/forums/topic/8280-server-game-log-server-stability-note-for-server-admins/

**Comment by Log1x** [comment]
Yeah, `-servergamelog` tends to crash servers very often. If someone types a percent sign (%) into your chat, it's an instant crash.

I do think `-servergamelog` would be the better option down the road, but until it's fixed, `GetChat` is probably the only sane choice.

Hopefully Wildcard fixes it one day. :frowning:

**Comment by klightspeed** [comment]
I reported this to their bug reporting forum a bit over a month ago:
http://steamcommunity.com/app/346110/discussions/9/352788552261287306/

(Note that the bug reporting forum is not visible unless you are signed into Steam)

**Comment by arkfrance** [comment]
I've just ask this to the Linux dev enginer, I'm waiting for his answer

**Comment by arkfrance** [comment]
No fix coming

**Comment by arkfrance** [comment]
Is it still possible to do something?

**Comment by StevenB83** [comment]
If you are willing to either risk using -servergamelog or using GetChat it's definately possible.
With GetChat you would either have to do it very often or there would be a large delay on the commands.
Which is why my crude scripts just uses -servergamelog. I'll paste it here incase it helps others :)

My scripts are divided into two separate scripts per server I run. One to monitor for new ServerGame file so it's always monitoring the latest and one for running the commands and cleanup on exit (ctrl+c). 
I have not made them run in screen or tmux as I personally have a few other scripts (chat log, chat send, playerlist and thecentercmd) running in a single tmux session.

<details>
<summary>thecentercmdkill</summary>
This one is not to be run separately, but thecentercmd will start it.
```
#!/bin/bash

inotifywait -m -e create -q --format '%f' /home/steam/thecenter/ShooterGame/Saved/Logs | while read LOGFILE
do
  [[ "{$LOGFILE}" == *"ServerGame"* ]] && pkill -f  "tail -F -n 1 /home/steam/thecenter/ShooterGame/Saved/Logs"
done
```
</details>
<details>
<summary>thecentercmd</summary>
```
#!/bin/bash

/home/steam/thecentercmdkill &

function cleanup {
  pkill -f  "thecentercmdkill"
  pkill -f  "tail -F -n 1 /home/steam/thecenter/ShooterGame/Saved/Logs"
}

trap cleanup EXIT

while [ 1 ]; do
  tail -F -n 1 `find /home/steam/thecenter/ShooterGame/Saved/Logs/ServerGame* -printf '%T+ %p\n' | sort | tail -1 | awk '{print $2}'` | while read LOGLINE
  do
    [[ "${LOGLINE}" == *"!help"* ]] && [[ "${LOGLINE}" != *"SERVER"*"!help"* ]] || [[ "${LOGLINE}" == *"@help"* ]] && [[ "${LOGLINE}" != *"SERVER"*"@help"* ]] && PLAYER="\""`echo "${LOGLINE}" |  grep -o -P '(?<=: ).*(?= \()'`"\"" && while IFS= read -r line; do arkmanager useconfig thecenter rconcmd 'ServerChatToPlayer '"$PLAYER"' '"$line"'' && sleep 2; done < /home/steam/help
    [[ "${LOGLINE}" == *"!rules"* ]] && [[ "${LOGLINE}" != *"SERVER"*"!rules"* ]] || [[ "${LOGLINE}" == *"@rules"* ]] && [[ "${LOGLINE}" != *"SERVER"*"@rules"* ]] && PLAYER="\""`echo "${LOGLINE}" |  grep -o -P '(?<=: ).*(?= \()'`"\"" && while IFS= read -r line; do arkmanager useconfig thecenter rconcmd 'ServerChatToPlayer '"$PLAYER"' '"$line"'' && sleep 4; done < /home/steam/rules && arkmanager useconfig thecenter rconcmd 'ServerChatToPlayer '"$PLAYER"' Use Page Up/Page Down to scroll in chat.'
    [[ "${LOGLINE}" == *"!players"* ]] || [[ "${LOGLINE}" == *"@players"* ]] && arkmanager useconfig thecenter rconcmd listplayers > /home/steam/thecenteronline && a=$(cat /home/steam/thecenteronline| wc -l /home/steam/thecenteronline|cut -c1-2) && online=$[$a-3] && arkmanager useconfig thecenter rconcmd 'ServerChat Players online: '$online' '
    [[ "${LOGLINE}" == *"!admin"* ]] && [[ "${LOGLINE}" != *"SERVER"*"!admin"* ]] || [[ "${LOGLINE}" == *"@admin"* ]] && [[ "${LOGLINE}" != *"SERVER"*"@admin"* ]] && PLAYER="\""`echo "${LOGLINE}" |  grep -o -P '(?<=: ).*(?= \()'`"\"" && tail -n 100 `find /home/steam/thecenter/ShooterGame/Saved/Logs/ServerGame* -printf '%T+ %p\n' | sort | tail -1 | awk '{print $2}'` | mail -s "Player '"$PLAYER"' used !admin command" YOUR@MAIL.ADR && arkmanager useconfig thecenter rconcmd 'ServerChatToPlayer '"$PLAYER"' Sent massage to Admin, will be in touch with you as soon as possible!'
    [[ "${LOGLINE}" == *"admin"* ]] && [[ "${LOGLINE}" != *"!admin"* ]] && [[ "${LOGLINE}" != *"SERVER"*"admin"* ]] || [[ "${LOGLINE}" == *"admin"* ]] && [[ "${LOGLINE}" != *"@admin"* ]] && [[ "${LOGLINE}" != *"SERVER"*"admin"* ]] && PLAYER="\""`echo "${LOGLINE}" |  grep -o -P '(?<=: ).*(?= \()'`"\"" && arkmanager useconfig thecenter rconcmd 'ServerChatToPlayer '"$PLAYER"' Need admin? Type @admin in chat.'
    [[ "${LOGLINE}" == *"Steven (Steven): !motd"* ]] && arkmanager useconfig thecenter rconcmd ShowMessageOfTheDay
  done
done
```
</details>
For this script I have two plain text files called help and rules in /home/steam.
In help I have one line explaining how to use commands and the rest of the lines are the commands with brief explanation.
The rules file contains the rules, one rule per line.

<details>
<summary>example help</summary>
```
Start commands with exclamation or at sign.
@help - this list.
@rules - server rules.
@players - players online.
@admin - sends message to admin.
```
</details>
<details>
<summary>example rules</summary>
```
Be respectful to other players.
Do NOT camp the coast if you are only there to kill people.
Griefing is allowed to an extent. You may grief a base just enough for you to gain access and complete your raid.
Killing other peoples dinos that aren't attacking you is NOT allowed.
Building bases inside or blocking access to caves containing loot/artifacts are NOT allowed and if found they will be demolished. (Bridges and helpful buildings while caving is allowed).
Use of the percentsign in Global or Local chat is strictly prohibited! Violations may result in a ban from the server.
```
</details>

If anyone has suggestions to improve on my crude script, please do suggest ^^

Steven.

**Comment by arkfrance** [comment]
does someone find a way ?

**Comment by Lihis** [comment]
I have written `arkwrapper` and tried to make it's chat functionality to be expandable by "plugins". I have wrote one, "admin plugin" for it which monitors chat for "!admin" message. One could make a "plugin" to achieve what one wants. Plugin enabled/disabled functionality might still need some improvements to make it more easier to use. And it supports only one instance. Arkwrapper can be found from: https://git.lihis.net/Lihis/arkwrapper/blob/master/arkwrapper

**Comment by arkfrance** [comment]
Nice, but i wanted more something like when someone type !rates or !rules a message is send back to them with some text

**Comment by Lihis** [comment]
You can write a "plugin" (aka. script) which that does that.

**Comment by arkfrance** [comment]
i'm not very good at scripting lol

**Comment by arkfrance** [comment]
Thanks Steven, one of the best features ever! Good luck

**Comment by StevenB83** [comment]
Just a little progress update, everything is now inside one script and commands work on all my servers with no hardcoded paths, I will make a config option to specify instances the commands should run on.
At the moment it only fetches the instances that reside in `/etc/arkmanager/instances`, so if your instances are not located there it would not currently work, I will implement all the folder locations that arkmanager currently looks for instances.

Script depends on arkmanager for sending the commands, I have no plans on implementing any form of rcon as that would be re-inventing the wheel. It also depends on inotifywait which on debian/ubuntu is part of the inotify-tools package to monitor for new ServerGame files being created upon server restart (and first event logged), this is the most robust method of watching for changes.

It spawns 1 inotifywait monitor process that monitors all the instances Logs folder and 1 tail process for each instance to watch the latest ServerGame file for any commands. In addition to the main script thread it spawns two extra per server so it can restart tail if a server restarts (a new ServerGame log file being created). For my 5 instances a total of 17 process threads are spawned, commands will run in parallel between servers, but on each server they are queued up atm. I may parallelize this further so that two or more commands per server get replied to instantly.

I still need to have commands be dynamically created from config options instead of hardcoded so it would be easier for people to make new commands.
With enough functions and explanation inside the config file on which function to call and what they do, it should be easy for people to create their own dynamic commands that would get variables from the different instance configs and such.
One example being rates which currently fetches the multipliers and such directly from Game.ini and GameUserSettings.ini.

If anyone has any suggestions I will do my best to implement them.

Steven.

**Comment by arkfrance** [comment]
@StevenB83 hey what's up ? any progress ?
