### ISSUE TITLE
rconcmd and broadcast saveworld sometimes fails to work

### ISSUE THREAD

**Issue by kdulep** [arkmanager/ark-server-tools#622]
arkmanager broadcast "Server restart 15 min"
Running command 'broadcast' for instance 'main'
Empty response at -e line 12.

list players also not working

**Comment by klightspeed** [comment]
There was a bug in arkmanager that did not detect an authentication failure.  v1.6.04 fixes this bug.

That version should now give "Authentication Failed" rather than "Empty response" when the password is incorrect or invalid.

Note that the server admin password cannot have any characters outside the [Basic Latin](https://en.wikipedia.org/wiki/Basic_Latin_\(Unicode_block\)) block, as even though Wildcard's ARK server does accept [UTF-8](https://en.wikipedia.org/wiki/UTF-8) encoded characters in any settings passed on the command-line, it does not accept characters outside the basic latin block (regardless of encoding) through RCON.

**Comment by kdulep** [comment]
last update, still not working it happens randomly after some time

**Comment by klightspeed** [comment]
When it fails, are you able to successfully perform a `EnableCheats <adminpassword>` then `ShowMyAdminManager` from the game client when this occurs?

**Comment by kdulep** [comment]
yes i can become admin

**Comment by klightspeed** [comment]
Would you please be able to do the following:
* Create a new file `rconcmd.sh` with the following contents:
```
#!/bin/bash

source /usr/local/bin/arkmanager
useConfig main
getAdminPassword
rconcmd "broadcast test"
```
* Run `chmod +x rconcmd.sh`
* Run `./rconcmd.sh` and confirm that it outputs your admin password, and that it processes the command successfully

**Comment by kdulep** [comment]
ok when i get stuck with commands not working i try it thanks
