### ISSUE TITLE
GameUserSettings for Mods

### ISSUE THREAD

**Issue by qroac** [arkmanager/ark-server-tools#637]
Is it possible to define values for non-official settings introduced by mods and placed in their own sections in GameUserSettings?

In my current case I would like to set custom sell prices for the Capitalism Sell Table for each server instance: http://steamcommunity.com/workshop/filedetails/discussion/748358288/343785574516572681/

This requires to be able to set values in sections that are written to GUS on server start.  
Maybe it could look like this to determine that it is a custom-section-value:  
ark__SectionName__ConfigParameter="value"

**Comment by Flukethoughts** [comment]
if your using different instances for each server they all have their own gameusersettings.ini which is why i dont understand why you would need to have a start parameter for it

For instance my six servers all have their own folder setup for each install.
The have their own save directories as well don't know if this differs from other installations but from common practice sharing resources such as files and game data never works out well in the end plus i didn't think it was an option. 

We have a user created in our linux directory called steam and it has full ftp and write and read prams on the directory. So while arkmanager runs as a service it allows the ability to change and edit files. 

if your sharing the folders data directories between all their servers I wouldn't be able to help you. however what your asking for would be messy from a personal perspective.

**Comment by theWeird** [comment]
So you do not just set individual AltSaveDirectoryName for your servers, you set different arkserverroot and have 8x the whole server setup?

**Comment by Flukethoughts** [comment]
No I use different instances like this
for instance center top lines read
# config environment
arkserverroot="/home/steam/center"
And island reads
# config environment
arkserverroot="/home/steam/island"

Each folder has it's own folder and on top of that each server has it's own gameusersettings.ini
