### ISSUE TITLE
Crontab and Automessage multi instance

### ISSUE THREAD

**Issue by ReaperBe7062** [arkmanager/ark-server-tools#653]
hello , 

i have a question i make 2 servers on my dedicated server but i need to make Automessage for eatch server's and but not the same for the 2 servers so can i make crontab's for one instance and a other crontab for my other server ? 

And i want to set a config for autoupdate for each server how i can i do that ? 

thanks a lot for ur helping :)

and thanks for ur amazing Script !

**Comment by dahlskebank** [comment]
I use this to check for and update both servers every 2 hours:
`00 */2 * * * /home/ark/bin/arkmanager update --safe --warn --saveworld --update-mods @all`
But I'm not 100% sure that it works. I just recently setup the second server, and it often looks like it doesn't update.

This sends a chat message from the server ingame:
`00 */4 * * * /home/ark/bin/arkmanager rconcmd 'ServerChat No Ark For Old Men: Arksanity.com [ORP]' @all`
Although I haven't really tested this either. It works on the default server, I haven't been much on the new one to notice it yet. 

Though, the directory above is where arkmanager is installed on my server, you may have to change that.

**Comment by Flukethoughts** [comment]
check the process tab watch it works but it works and overlaps which causes the issue this is what i have been dealing with and its annoying as hell. Checks update then somehow gets a horrible steam server for download and downloads everything then while in the process of updating time has gone by and it has started the update cronjob again which overlaps and causes strain

**Comment by klightspeed** [comment]
If you have `&` at the end of the command in your crontab, then you are bypassing cron's protection against this occurring - the cron daemon should not allow multiple instances of a single cron job to run simultaneously.
If you are removing the `.arkupdate.lock` file, then you are bypassing arkmanager's protection against this occurring.

**Comment by dahlskebank** [comment]
One a sidenote for crontab, multi-instance and auto-update, the following is not working for me.
`00 */2 * * * /home/ark/bin/arkmanager update --safe --warn --saveworld --update-mods @all`

Perhaps someone can fill me in here, this will also be useful for @ReaperBe7062, but when that is run either via crontab or just command line, it doesn't stop both servers. It will start with the first server and if there is an update, it will countdown 15 minutes warning the players, saveworld, stop server, update, start server.

And then it starts to check for update for the second server. But these files have already been updated by the first server, so it won't update. Leaving the second server without getting updated... Even though the files are updated, the server isn't restarted so that the version number updates.

Am I doing this wrong? Is there some other way? I'd prefer to keep checking for updates automatically as often as possible, so that I can stop playing ARK and let the server run it's course. I run a nightly stop and saveworld of both servers so that I can get an offsite backup, so the second server will eventually be updated... still, I'd prefer it to auto-update every 2 hours like the other server.
