### ISSUE TITLE
arkmanager status command says server is offline when it is online

### ISSUE THREAD

**Issue by Rob-bb** [arkmanager/ark-server-tools#663]
hi, here is the output from arkmanager status

```
Running command 'status' for instance 'grounded'
 Server running:   Yes 
 Server listening:   Yes 
Server Name: [NZ-AU] Grounded (http://grounded.trivial.nz)  - (v251.3)
Players: 1 / 70
Active Players: 1
 Server online:   No 
 Server build ID:   1470493 
 Server version:   251.3 
```

It says "Server online:   No"  while it is on.  Not sure if this is arkmanager error or if the server is miss-reporting it's status.

**Comment by klightspeed** [comment]
`Server online: no` means that it is not listed on the Steam master server under the configured IP address and port.

**Comment by CaspyBXL** [comment]
@rob-bb
Maybe i can be of help here. So i have had this issue before on ark where you install a server boot it and even after 24h still not showing up online.

Can you show the code for the .cfg ?
                                 
ark_Port=
ark_bRawSockets=
ark_QueryPort=

i'm sure it will be that kind of issue !

**Comment by rob-bb** [comment]
Hi, I have ark_bRawSockets=true, and am forwarding both tcp and udp for the ports used by  ark_Port and ark_QueryPort

**Comment by CaspyBXL** [comment]
@rob-bb

I see more then one thing that can interfere.

When Klightspeed says "not listed on the Steam master server" this can be one of the next reasons : 

Steam Master server don't like --> http://grounded.trivial.nz/ --> for the // and : in the links
Or Steam Master server does not recognize the port you are using. 

My configs are like this : 

serverMap="TheIsland"                                        
ark_RCONEnabled="True"
ark_RCONPort="32330" 
ark_Port="7782"
ark_bRawSockets="True"
ark_QueryPort="27015"

serverMap="TheVolcano"                                        
ark_RCONEnabled="True"
ark_RCONPort="32430" 
ark_Port="7780"
ark_bRawSockets="True"
ark_QueryPort="27016"

serverMap="TheCenter"                                        
ark_RCONEnabled="True"
ark_RCONPort="32530" 
ark_Port="7778"
ark_bRawSockets="True"
ark_QueryPort="27017"

With the RawSockets you must then open up ports : 

Island
Forward 7777 to 7778
Allow Traffic on 7778

Volcano
Forward 7779 to 7780
Allow Traffic on 7780

Center
Forward 7781 to 7782
Allow Traffic on 7782

Works Fine for my Linux Debian 8
Also i use UFW and not direct IP tables, turns out to be more easy to get configs up

If you want some help we could talk it over on teamspeak or so.

**Comment by rob-bb** [comment]
Ok, I am forwarding all the ports from my router direct to the server, I will try removing the http:// and double check the ports/firewall settings and see if that helps, after that I might take you up on the team speak chat.

**Comment by CaspyBXL** [comment]
Sure thing ! You helped me with Cron so the least i could do is offer to try and help you out with this !

**Comment by rob-bb** [comment]
It seems you were rights, I removes the http:// stuff and now it is showing up in the lists again.

**Comment by CaspyBXL** [comment]
Happy to help out ! <3

**Comment by SinisterSole** [comment]
@klightspeed 
"Server online: No" could also mean there was a problem with the security certificate on https://api.ipify.org/. I had the same problem until I edited the command to http://api.ipify.org/. This does not show up when using the -s (silent) switch in curl. I am not a wiz at http but does this impact any security protocols when processing the command?
