### ISSUE TITLE
Cluster setup pointers

### ISSUE THREAD

**Issue by joebywan** [arkmanager/ark-server-tools#738]
...

**Comment by rlex** [comment]
Will you host it on same machine?
~/.config/arkmanager/instances files:

theisland.cfg
```
# arkmanager settings
arkserverroot="/home/gs-ark/arkservers/theisland"
arkbackupdir="/home/gs-ark/ARK-Backups/TheIsland"

# ark server settings
serverMap="TheIsland"
ark_SessionName="servername - The Island"
ark_Port="7778"
ark_QueryPort="27020"
ark_ServerAdminPassword="your_admin_password"
ark_RCONEnabled="True"
ark_RCONPort="32332"
ark_MaxPlayers="40"
ark_GameModIds="821530042,572277026,655261420,756389708,793605978,737297870,718412068"
ark_AltSaveDirectoryName="Saved-TheIsland"

# ark cluster settings
arkflag_NoTransferFromFiltering=""
arkopt_clusterid=pvearkcluster
#ark_PreventDownloadSurvivors=False
#ark_PreventDownloadItems=False
#ark_PreventDownloadDinos=False
#ark_PreventUploadSurvivors=False
#ark_PreventUploadItems=False
#ark_PreventUploadDinos=False
#ark_noTributeDownloads=false
arkopt_ClusterDirOverride=/home/gs-ark/arkservers/clusterdata
```
scorchedearth.cfg:
```
# arkmanager settings
arkserverroot="/home/gs-ark/arkservers/scorchedearth"
arkbackupdir="/home/gs-ark/ARK-Backups/ScorchedEarth"

# ark server settings
serverMap="ScorchedEarth_P"
ark_SessionName="servername - Scorched Earth"
ark_Port="7782"
ark_QueryPort="27021"
ark_ServerAdminPassword="your_admin_pass"
ark_RCONEnabled="True"
ark_RCONPort="32333"
ark_MaxPlayers="40"
ark_GameModIds="821530042,572277026,655261420,756389708,793605978,737297870,718412068"
ark_AltSaveDirectoryName="Saved-ScorchedEarth"

# ark cluster settings
arkflag_NoTransferFromFiltering=""
arkopt_clusterid=pvearkcluster
#ark_PreventDownloadSurvivors=False
#ark_PreventDownloadItems=False
#ark_PreventDownloadDinos=False
#ark_PreventUploadSurvivors=False
#ark_PreventUploadItems=False
#ark_PreventUploadDinos=False
#ark_noTributeDownloads=False
arkopt_ClusterDirOverride=/home/gs-ark/arkservers/clusterdata
```

Critical params are:  
arkflag_NoTransferFromFiltering="" - should prevent uploading data to your server from other clusters / local saves
arkopt_clusterid=pvearkcluster - internal cluster name, can be useful if you run pvp and pve clusters on same box
arkopt_ClusterDirOverride=/home/gs-ark/arkservers/clusterdata - shared dir with cluster data, should be writable by ARK server

```
#ark_PreventDownloadSurvivors=False
#ark_PreventDownloadItems=False
#ark_PreventDownloadDinos=False
#ark_PreventUploadSurvivors=False
#ark_PreventUploadItems=False
#ark_PreventUploadDinos=False
#ark_noTributeDownloads=False
```
Everything to "False" should be default settings, at least it works for me, so it's commented out.

**Comment by joebywan** [comment]
Thanks dude.  Got it working.

Figured out that you don't need arkflag_NoTransferFromFiltering="" or arkopt_clusterid=pvearkcluster in the individual cfg's, you only need them in the arkmanager.cfg.

You also don't need different server root.  Just use the same one and run it all from the one install.

**Comment by rlex** [comment]
>Figured out that you don't need arkflag_NoTransferFromFiltering="" or arkopt_clusterid=pvearkcluster in the individual cfg's, you only need them in the arkmanager.cfg

If you run one cluster, then yes

>You also don't need different server root. Just use the same one and run it all from the one install.

I do not recommend that, it causes all kinds of problems.

**Comment by joebywan** [comment]
What problems?  It's all working fine atm.

**Comment by rlex** [comment]
most notably automated updates like "arkmanager update --update-mods --backup @all" will not work, it will only restart first instance (since it received update), so your first shard will be updated, while secondary servers will be stuck with old version (since update check will show that it already up-to-date).
Also it overwrites configuration file (GameUserSettings.ini) every time you start server.
Also i noticed that ark server spamming something like "stop running multiple servers from one directory". Sadly my logs has been rotated and i can't provide you with exact message.

**Comment by joebywan** [comment]
overwriting the gameusersettings.ini doesn't really matter if the .cfg's are setup correctly.

I've run updates on the instance already and had no issues, maybe you're using an old version of the script?

**Comment by cronner** [comment]
this guide claims that it only needs one install? https://survivetheark.com/index.php?/forums/topic/87419-guide-cluster-setup/

**Comment by TexanFoxx** [comment]
joebywan, could you by chance paste the cfgs with names? I'm assuming you setup the cfgs similar to rlex and then ran the arkmanager install @all, arkmanager start @all after you setup said cfgs and you were good?

**Comment by VorlMaldor** [comment]
I have been looking at the second response and can't figure out what I am doing wrong.

arkflag_NoTransferFromFiltering=""
arkopt_ClusterDirOverride="/home/steam/clusters"
arkopt_clusterid="cluster1"

That is in each of our /etc/arkmanager/instances/ cfg files.

Do I have something wrong in those entries?  We have the servers configured for ports 7777 and 7778 (7778 and 7779 in the cfg because of the +1), ports 27015 and 27016 open, and our rcon mores. We can connect to each of them separately, but can't get them to see a cluster. 

Here are the two command lines that arkmanager is creating as shown in the logs:

[2017.05.27-19.45.43:792][  0]Commandline:  "TheVolcano?MapModID=715028562?RCONEnabled=True?RCONPort=32331?SessionName=The bob?Port=7778?QueryPort=27016?ServerPassword?ServerAdminPassword=bob?MaxPlayers=45?GameModIds=538986229,764755314,630601751,751991809,812655342,821530042,601893934,741203089,677673057,793605978?OverrideOfficialDifficulty=5?listen" -ForceAllowCaveFlyers -NoTransferFromFiltering -ClusterDirOverride=/home/steam/clusters -clusterid=cluster1

[2017.05.27-19.47.01:844][  0]Commandline:  TheIsland?RCONEnabled=True?RCONPort=32330?SessionName=Bob?Port=7777?QueryPort=27015?ServerPassword=bob?ServerAdminPassword=bob?MaxPlayers=40?GameModIds=764755314,630601751,751991809,812655342,821530042,601893934,741203089,677673057,793605978?listen -NoTransferFromFiltering -ClusterDirOverride=/home/steam/clusters -clusterid=cluster1

Thoughts? 

Thank you!

**Comment by Daddioo** [comment]
@VorlMaldor 
use:
ark_ClusterDirOverride=
ark_clusterid=
*Dont need the NoTransferFromFiltering

**Comment by waltzie** [comment]
You have to change the  -clusterid=[Unique ID value]

**Comment by VeaexYT** [comment]
ark@vmd24450:~/arkserver$ arkmanager install @ALL
Running command 'install' for instance 'ALL'
Error: no config files for instance ALL

**Comment by klightspeed** [comment]
@VeaexYT please try `@all`

**Comment by VeaexYT** [comment]
@klightspeed it worked thx
