### ISSUE TITLE
Cluster on two different servers(different Pc's)

### ISSUE THREAD

**Issue by Stray-Fenris** [arkmanager/ark-server-tools#993]
I have switched to a newer Pc(was my gamepc,then a few years as a company-pc and got now replaced, so back in my hands), which has 8 cores, so i wanted to run two servers, sadly, i realised now, that it has only 8GB Ram max, which is not enough to start two non-Dlc servers, not even talking about 2 servers with EC. 

So here i am, debating wether i should reactivate my old server as well or if there is another solution. Also, i would love to know how the cluster function works, because it's most likely, that i will need to use it

**Comment by klightspeed** [comment]
The instances need access to a shared directory, which contains data passed between the instances in the cluster.

**Comment by Stray-Fenris** [comment]
@klightspeed Sooo, would a external harddrive in the network do the trick?

**Comment by CaspyBXL** [comment]
Dear @klightspeed 

I have an update for you what might lead you on to something or help even others.

I was working on some kind of test.
Its my understanding if the 2 server have the same folder setup and same users and permissions the info does go from one to another cluster. Don't ask me how or what .. it just does ...
I have cluster on SERVER A linked to cluster on SERVER B wich is an exact replica of server A (but not a clone). Just set up and scripted the same way.

My people have been transfering from Server A to B since 3 weeks now.
The servers are Phisical Servers and on completely isolated networks.
I use to do this on VM's in the pas with a shared folder for the servers, but now that it works we can once again enjoy the full power of non virtualised servers with still a way to link clusters.

@Stray-Fenris 
I would suggest to specify it in the XXX.cfg inside /etc/arkmanager/instances as demanded

arkopt_ClusterDirOverride="/home/steam/5-way-cluster" --> change this to the /media/XXX for a mounted media or if you use NFS or CIFS you could bind it on your own /XXX at the root of the server.
arkopt_clusterid=XXXXXXXXX

**Comment by klightspeed** [comment]
> Its my understanding if the 2 server have the same folder setup and same users and permissions the info does go from one to another cluster. Don't ask me how or what .. it just does ...

This suggests that inter-server communication is set up when transferring.  I wonder if this means that the cluster ID now needs to be universally unique, and not just unique to the server it's running on?

**Comment by CaspyBXL** [comment]
I you are up for some testing I can manage some 2 Linux Servers to test this Klightspeed, i'll be happy to give you some resources if needed. Always happy to help out !

**Comment by dahlskebank** [comment]
> This suggests that inter-server communication is set up when transferring. I wonder if this means that the cluster ID now needs to be universally unique, and not just unique to the server it's running on?

Cluster ID needs to be universally unique. If you try with like 123, you'll get tons of other servers showing up when you wanna transfer, but due to not sharing write privileges with the cluster-files, your char and items can't be moved there (without enabled filtering setting).

Someone solved the "on different networks" cluster thingy, I assume the same could be applied even if on same network (never tested myself): https://survivetheark.com/index.php?/forums/topic/300528-set-up-server-cluster-on-different-networks/

**Comment by NobodyDz** [comment]
Use syncthing https://syncthing.net/
